# Getting Started prometheus configuration
# Check config: promtool check config prometheus.yml
global:
  scrape_interval: 60s   # Default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'linux_node_exporter'
    scrape_interval: 10s  # Scraping frequency can affect CPU
    file_sd_configs:
      - refresh_interval: "5m"
        files:
          - './targets/node_exporter.json'

